CI update
Signed-off-by: Abhijith Ganesh <git.watch.abhijith@outlook.com>

diff --git a/.github/workflows/nextjs.yaml b/.github/workflows/nextjs.yaml
--- a/.github/workflows/nextjs.yaml
+++ b/.github/workflows/nextjs.yaml
@@ -7,7 +7,7 @@ name: Deploy Next.js site to Pages
 on:
   # Runs on pushes targeting the default branch
   push:
-    branches: ["*"]
+    branches: ["2023-website", "Brainstorming"]
 
   # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
@@ -34,7 +34,15 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
-            "npm i"
+          if [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+            echo "command=ci" >> $GITHUB_OUTPUT
+            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+            exit 0
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
